### ISSUE TITLE
Error in examples 

### ISSUE THREAD

**Issue by shravya-ks** [Tejeshwarabm/MADPIE#4]
Hello guys, 
When I ran your examples, I am getting the following error.
 In function ‘void CheckQueueDelay(ns3::Ptrns3::QueueDisc)’:
../scratch/first-bulksend.cc:57:69: error: cannot convert ‘ns3::Time’ to ‘uint32_t {aka unsigned int}’ in initialization
   uint32_t qSize = StaticCast<PieQueueDisc> (queue)->GetQueueDelay ();
                                                                     ^
Can you fix this issue in all examples?
Hint : You need to use the function GetSeconds( )

**Comment by Tejeshwarabm** [comment]
first-bulksend.cc
I have fixed those error in first example and now is its compiled successfully.

**Comment by mohittahiliani** [comment]
Closing.
